<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="W1071DXQQ2" ignored="0" name="Default test" tests="2" failures="1" timestamp="17 Sep 2021 10:21:32 GMT" time="36.931" errors="0">
  <testcase name="enterCredentials" time="14.648" classname="com.pom.testcases.TestFacebookLoginPage"/>
  <testcase name="getLoginError" time="21.517" classname="com.pom.testcases.TestFacebookLoginPage">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [ The password that you&amp;apos;ve entered is incorrect. Forgotten password?] but found [The password that you&amp;apos;ve entered is incorrect. Forgotten password?]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [ The password that you've entered is incorrect. Forgotten password?] but found [The password that you've entered is incorrect. Forgotten password?]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.pom.testcases.TestFacebookLoginPage.getLoginError(TestFacebookLoginPage.java:88)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- getLoginError -->
</testsuite> <!-- Default test -->
